version: '3'
 
services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    build: .
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    build: .
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres
 
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: pass123
      RABBITMQ_DEFAULT_USER: backend_service
    image: "rabbitmq:3-management-alpine"
    ports:
      - "15972:15672"
      - "5672:5672"
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo_express:
    image: mongo-express
    depends_on:
      - mongodb_container
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_container
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
    ports:
      - 8081:8081
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  ibank-gateway:
    build:
      context: ./ibank-gateway
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server

  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server

  account-service:
    build:
      context: ./account-service
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server

  customer-support-service:
    build:
      context: ./customer-support-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server

volumes:
  redis:
  redis-config:
  mongodb_data_container:
networks:
  redis-network:
    driver: bridge
