
spring:

  application:
    name: customer-support-service
  cloud:
    function:
      definition: supportTicketBinding
    stream:
      bindings:
        supportTicketBinding-in-0:
          destination: ticket
          group: tickets
        supportTicketBinding-out-0:
          destination: ticket
          producer:
            required-groups: tickets

  data:
    mongodb:
      #uri: mongodb://root:admin@localhost:27017/tickets
      authentication-database: admin
      username: root
      password: mongodb
      host: mongodb_container
      database: tickets
      port: 27017
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: backend_service
    password: pass123

server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    hostname: customer-support-service

auth:
  secret-key: ${SECRET_KEY:5367566B59703273357638792GSFHSTTHHS52241255555552212}

token-duration:
  access-token: 300 #5 seconds

client:
  name: ibank-web-frontend
  scope: ibank:service-request
logging:
  level:
    org.springframework.cloud.stream: DEBUG