spring:
  application:
    name: ACCOUNT-SERVICE
  cloud:
    function:
      definition: transactionBinding
    stream:
      bindings:
        transactionBinding-in-0:
          destination: transaction
          group: transactions
  data:
    redis:
      host: redis
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: backend_service
    password: pass123
  r2dbc:
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    url: ${R2DBC_DATABASE_URL:r2dbc:postgresql://postgres:5432/ibank_account}
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://postgres:5432/ibank_account}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://postgres:5432/ibank_account}

server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    hostname: account-service

auth:
  secret-key: ${SECRET_KEY:5367566B59703273357638792GSFHSTTHHS52241255555552212}

token-duration:
  access-token: 300 #5 seconds

client:
  name: ibank-web-frontend
  scope: ibank:service-request
logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.data.redis: DEBUG